### PR TITLE
Add ticks to code and code-like stuff

### PR DESCRIPTION
**Pull request by BrandonHaynes**

### CODE REVIEW

**Comment by senderista** [comment]
This looks like the old README in master, not the heavily revised one in the reef branch.

**Comment by BrandonHaynes** [comment]
Um, oops.  This will also apply to http://myria.cs.washington.edu/docs/myria-ec2.html

**Comment by senderista** [comment]
Yeah, I copied the reef branch README to that page before the demo :)

**Comment by senderista** [comment]
If there's anything in the README on the `reef` branch that needs fixing, please add commits for that, otherwise let's close this.

**Pull request closed without merging**
